version: '3'

services:
  #MySQL用コンテナ
  # mysql:
  #   container_name: mysql
  #   image: mysql:5.7
  #   volumes:
  #     - ./mysql:/var/lib/mysql
  #   ports:
  #     - 3305:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=test
  #     - MYSQL_USER=test
  #     - MYSQL_PASSWORD=test
  php:
    container_name: php-apache
    build: ./php
    volumes:
      - ./html:/var/www/html
    ports:
      - 8080:80
    # depends_on:
    #   - mysql
